name: Publish Docker image - aws-cost-to-prometheus

on: 
  push:
    branches:
     - main
    paths:
      - "**"
      - '!renovate.json'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub - aws-cost-to-prometheus
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: antlac1/aws-cost-to-prometheus

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./getFiles-node
          file: ./getFiles-node/Dockerfile
          push: true
          platforms: linux/amd64
          tags: antlac1/aws-cost-to-prometheus:latest
          labels: ${{ steps.meta.outputs.labels }}